# Generated by Django 5.2.7 on 2025-10-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='blas@gmail.com', max_length=254),
        ),
    ]
